### ISSUE TITLE
feature_request: Vertical movement obey indentation

### ISSUE THREAD

**Issue by felipejoribeiro** [Jorengarenar/vim-MvVis#1]
Would be nice if the vertical movement could obey indentation. Because as it stands now. The line is moved as it is and after moving then you must adjust indentation.

Thank you for the awesome plugin.

**Comment by vzytoi** [comment]
Hey! I also think that is a nice feature, since it's not by default in the plugin :
```
vmap H <Plug>(MvVisLeft)=gv
vmap J <Plug>(MvVisDown)=gv
vmap K <Plug>(MvVisUp)=gv
vmap L <Plug>(MvVisRight)=gv
```
`=` allows you to indent the visual selected lines and `gv` reselect it.
Have a nice day!

**Comment by Jorengarenar** [comment]
Yup, mappings by @vzytoi solve the request

**Comment by felipejoribeiro** [comment]
Thank you! Now it's perfect. I can confirm that this solved here as well.
